apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: web:latest  # Remplacez par le nom réel
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: BACKEND_URL
          value: http://backend-service.backend.svc.cluster.local

