apiVersion: v1
kind: Service
metadata:
  name: mongo-service
  namespace: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  clusterIP: 10.152.183.1  # Headless service for direct access (optional)

