apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: mongo
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mongo"  # à adapter selon votre environnement

